### PR TITLE
Created initial UML diagram for alpha release

### PR DESCRIPTION
**Pull request by yehandesilva**
Creating this as a draft pull request as it is not complete, but is required for the completion of everyones tasks for the next milestone.

I have created the initial UML diagram which shows all Models that we will have including their fields (Methods are still empty). Keep in mind that this diagram is final as we are not adding any new Models in any future milestones.

Go through the diagram and see if anything is missed or incorrect.

### My thinking
- Use inheritance as discussed in #4 to create a super class for question and response
- Account has a list of suverys, each survey has a list of questions, and each question has a list of responses
- The ChoiceQuestion has a list of ChoiceOptions, and so ChoiceOption will have its own table
- Reponse has email field to prevent duplicate users from responding to a survey

### CODE REVIEW

**Comment by pathumd** [comment]
Nice work Yehan. There are a a couple of things I found:

- In Question Entity, typo in responses field -> should be 'List<Response>'

Design feedback:

- Currently, the Question class has a List of Response objects. This attribute is then inherited by the concrete implementations of Question: TextQuestion, NumberQuestion, ChoiceQuestion. TextQuestion is expecting its responses attribute to contain a list of TextResponse objects, the NumberQuestion is expecting its responses attribute to contain a list of NumberResponse objects, and the ChoiceQuestion's response attribute to contain a list of ChoiceResponse objects. The issue with this is that, any concrete implementation of Question can have responses of any of the three types (TextResponse, NumberResponse, ChoiceResponse). For example, TextQuestion could have a list of NumberResponses. To avoid this, this responses attribute should **not** be inherited, but instead defined in each concrete implementation of Question. This way, each concrete implementation can explicitly define which type of Response its responses attribute should contain. By doing so, the Response parent class can also be removed as it is no longer needed.

**Review by pathumd — CHANGES_REQUESTED** [review]
Nice work Yehan. There are a a couple of things I found:

In Question Entity, typo in responses field -> should be 'List'
Design feedback:

Currently, the Question class has a List of Response objects. This attribute is then inherited by the concrete implementations of Question: TextQuestion, NumberQuestion, ChoiceQuestion. TextQuestion is expecting its responses attribute to contain a list of TextResponse objects, the NumberQuestion is expecting its responses attribute to contain a list of NumberResponse objects, and the ChoiceQuestion's response attribute to contain a list of ChoiceResponse objects. The issue with this is that, any concrete implementation of Question can have responses of any of the three types (TextResponse, NumberResponse, ChoiceResponse). For example, TextQuestion could have a list of NumberResponses. To avoid this, this responses attribute should not be inherited, but instead defined in each concrete implementation of Question. This way, each concrete implementation can explicitly define which type of Response its responses attribute should contain. By doing so, the Response parent class can also be removed as it is no longer needed.

**Review by MichaelKyrollos — CHANGES_REQUESTED** [review]
Thank you for creating the initial design—it looks great! I did notice, though, that with the current setup, checking if a user has already submitted a survey might require querying multiple tables, such as survey questions and responses, to verify completion. To reduce the number of queries needed, maybe we could structure it so each response is directly associated with an email. This way, checking for survey completion would be faster and more efficient by only querying the responses. Just an idea to consider for optimization

Another option:
A more efficient approach could involve introducing a 'UserSurvey' table to track each user's survey completion status directly.
This table could store entries with user IDs, survey IDs, and completion statuses, allowing for quick, single-record lookups to determine if a user has completed a survey. This would reduce the need to scan the 'Responses' table and would streamline survey status checks, especially as data volume increases.

**Comment by yehandesilva** [comment]
I read both of your feedback and it makes sense. Need a more efficient way to prevent duplicate survey responses. The problem we have is that our requriements state that anyone (Doensn't neccessairly need to create an account) with the survey link should be able to fill out the survey, so we can't have UserSurvey table as @MichaelKyrollos mentioned as it can only store registered responses. I believe @AminZeina points this out too. I do like the suggestion of creating another table that stores respondees. Essentially, each row in the table would be a survey id and email which would allow us to quickly check if an email has responded to the given survey before.

I'll make those new changes and we can get started after that since the data structure is now finalized.

**Pull request closed without merging**
