### PR TITLE
Update README for early prototype

### LINKED ISSUE #27: Update README for Early Prototype
After implementation for Milestone 1 has been completed, the README must be updated to include instructions on how to run the application and other relevant tasks.

### PR DESCRIPTION
**Pull request by yehandesilva**
Closes #27 

Finished README for early prototype. Followed instructions and should have all the necessary sections.

If you have anything that needs to be added, feel free to add it. Can also take a look at our plan for the next milestone to see if it should be changed or things should be added.

### CODE REVIEW

**Comment by yehandesilva** [comment]
@pathumd Can you check if the new logo is displayed on the README once you've merged #31

**Review by MichaelKyrollos — APPROVED** [review]
Looks good! I'll be updating with the schemas once they are done.

**Comment by yehandesilva** [comment]
@MichaelKyrollos You'll need to update the diagrams on the README after you've finished #21

**Review by pathumd — APPROVED** [review]
README looks good to me, it contains all the required information, especially a detailed instructions on how to run the project. Nice job! There is one small typo I found under 'Milestone 1 - Early Prototype', where the fourth bullet starts with 'Developped'. But this is pretty minor and can be changed later.

**Review by AminZeina — APPROVED** [review]
Readme looks great! As just mentioned the build instructions are clear and a great addition. Approved!

**Pull request merged**
