### PR TITLE
Survey Creation Page

### LINKED ISSUE #42: Add interface for creating a Survey
We need to have a page for the user to create a survey. The page should likely be a form where the user can add a list of different question types, and then eventually POST the survey to the relevant Survey Controller endpoint defined in #41 . 

This page should only be available to authenticated users, so the user will have to login to access it. There should be a button somewhere on the user's home page (after log in) that loads this form.

### PR DESCRIPTION
**Pull request by AminZeina**
Created a frontend page for a user to create surveys. The page is dynamic and allows the user to add multiple Questions. Currently marking this as a draft awaiting completion of #41 as some changes may be needed based on what is returned by the `create-survey` endpoint once created (e.g., we may want to show what the created survey ID is). 

Each question is a card which contains a text field for the question prompt, a dropdown to select the question type, and then a dynamically-loaded set of option selection components based on the selected question type. For NumberQuestions, the selection options are a minimum value and maximum value number input field. For ChoiceQuestions, there are buttons to select the number of options, and then that number of text fields will be generated for the user to input each option. 

To access the page, a button has been added to the User's homepage.

A screenshot of the page, and the resulting JSON of the survey (which is generated on click of the **Create Survey!** button is below:

createSurveyScreen

```
{
    "1": {
        "prompt": "First question prompt",
        "type": "text",
        "responseOptions": {}
    },
    "2": {
        "prompt": "Second question prompt",
        "type": "number",
        "responseOptions": {
            "min": 1,
            "max": 5
        }
    },
    "3": {
        "prompt": "Third question prompt",
        "type": "choice",
        "responseOptions": {
            "option-1": "First response choice",
            "option-2": "Second response choice",
            "option-3": "Third response choice",
            "option-4": "Fourth response choice"
        }
    }
}
```

This closed #42 .

### CODE REVIEW

**Comment by yehandesilva** [comment]
Looks good! Exactly how I would have done and the question compoents look good. Just need to interface with the backend now.

**Comment by MichaelKyrollos** [comment]
Hey looks great! It looks like the JSON you send might have to change format, I am working on the POST but once I have a solid format, I will send it over to you so you can make the changes

**Comment by pathumd** [comment]
Apologies for the late review @AminZeina, but after going through your changes, the way you implemented the survey creation looks good to me. Nice work!

**Comment by MichaelKyrollos** [comment]
Good work! The blocking PR which is #63 is now merged, you can create a survey. Please also add the ability to put a survey title in the UI. As well the JSON for creating a survey has change: 

#### **POST /user/survey**
   This endpoint allows authenticated users to create a survey. The user must be logged in to create a survey.

   **Request Body Example:**
   ```json
   {
       "description": "Survey",
       "closed": false,
       "questions": [
           {
               "question": "Describe your work experience.",
               "type": "TextQuestion"
           },
           {
               "question": "What's your favorite video game?",
               "type": "ChoiceQuestion",
               "options": [
                   { "description": "Fortnite" },
                   { "description": "Forza" },
                   { "description": "Mario-Kart" }
               ]
           },
           {
               "question": "What's your age?",
               "type": "NumberQuestion",
               "minValue": 0,
               "maxValue": 100
           },
           {
               "question": "Describe your work experience.",
               "type": "TextQuestion"
           }
       ]
   }
   ```
   
   
   
   and the response: 
   
` {"message":"Survey successfully created!", "surveyId":2}`

**Comment by AminZeina** [comment]
Thanks for the feedback and for letting me know what changes needed to be made to the JSON. I've implemented these changes and the produced JSON now matches what is expected above. I've also updated the endpoint on the frontend side and added input validation to the Form.

**Comment by AminZeina** [comment]
All suggested changes have been implemented, including:
- Changing format of generated JSON to be sent to backend
- Updating endpoint to `/user/survey`
- Adding Text field for user to input a Survey Name
- Adding validation on the form to ensure no required values are left blank
  - Note that for choice questions, the number of entered questions does not need to match the selected number of questions; as long as there is at least one option entered, it is valid
 
After successful creation, the user is returned to their home page; we may want to change this in the future. Please take a look and let me know if anything needs to be changed.

**Review by MichaelKyrollos — APPROVED** [review]
This is great work! I tested everything out. It checks out. UI looks great too

**Comment by pathumd** [comment]
Nice work Amin! After manually testing your changes, adding questions and creating a survey works as expected. As @MichaelKyrollos mentioned I think you did a great job with the UI; it makes it easy for the user to create a question, choose its type, and create a survey.

One minor issue that I was able to find is, when adding a number question and typing 0 as the minimum value, clicking 'Create Survey' shows an error message saying that a minimum value hasn't been specified, as shown in the screenshot below:

Screenshot 2024-11-24 at 8 12 05 PM

**Review by pathumd — APPROVED** [review]
Fix solves the issue now @AminZeina. Good work

**Pull request merged**
