### PR TITLE
Created Account Controller and Implemented authentication

### LINKED ISSUE #30: Implement user authentication for AccountController endpoints
We need to implement an authentication mechanism for the AccountController to use to authenticate logins and registrations. 

This blocks #19 (need authentication mechanism to create a login endpoint) and is blocked by #18 (need an Account entity and repository to implement in a UserDetailsService).

Supporting documentation on how this can be done:
[Username/Password Authentication](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/index.html)

[Implementing User Authentication in a Spring Boot Application](https://medium.com/@abhinavv.singh/implementing-user-authentication-in-a-spring-boot-application-a-detailed-step-by-step-guide-b15a9877569b)

### PR DESCRIPTION
**Pull request by AminZeina**
### Additions

Created a basic Account Controller with two endpoints: `/login` and `register`. Also created a unit test for the controller using MockMvc, and tested creating an account and logging into an account. This closes #30 and potentially #19.

Authentication is done using [Spring Security](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/index.html#servlet-authentication-unpwd) - more resources can be found in #30. The majority of the additions in this PR are for implementing authentication and there's quite a bit to go through. But future feature branches for endpoints should be a lot smaller and quicker now that authentication is all set up.

### Future work
We still need to add input validation to the endpoints on the server side, and we may need to adjust what is returned by these endpoints depending on what the frontend needs. We can decide whether that should be a new issue or included with #19 - I think this mainly depends on how we prioritize our time between now and Nov. 11, as the priority should be getting the early prototype working.

### Example requests
Some example requests are below while waiting to get access to the postman shared space:

- creating a new account:
    - if email is already in use, 409 is returned
```
POST localhost:8080/register
{
    "email":"johndoe@email.com", 
    "password":"password123",
    "firstName":"John",
    "lastName":"Doe"
}
```

- logging into an account 
    - if username (email) does not exist or password is incorrect, 401 is returned
```
POST localhost:8080/login
{
    "email":"johndoe@email.com", 
    "password":"password123"
}
```
See the Unit test for more examples.

### CODE REVIEW

**Review by MichaelKyrollos — APPROVED** [review]
Just tried the changes, everything seems to be working. Good work! Just gonna need a demo on a few uncertainties

**Review by pathumd — CHANGES_REQUESTED** [review]
The implementation of the Spring authentication and Account Controller looks good and makes sense. The tests that were written in AccountControllerTest are all passing. However, when running the application, I'm having trouble accessing the default route ('/'), which should be returning index.html. Instead, I'm provided a sign-in page that seems to continuously authenticate you.
Screenshot 2024-11-10 at 9 57 10 AM

**Comment by MichaelKyrollos** [comment]
Also, this is related to issue #20

**Comment by AminZeina** [comment]
The most recent changes fix the issues with the return types of these endpoints as mentioned in #19 . Both endpoints now return valid JSON which can be properly consumed by the frontend.

**Review by yehandesilva — APPROVED** [review]
Looks good. Was able to run successfully.

**Pull request merged**
