### PR TITLE
Creation of Account Entity

### PR DESCRIPTION
**Pull request by pathumd**
- Created the Account class, which models the Account entity for the MonkeyPoll application

Other minor changes:
- Added additional dependencies to pom.xml file, including dependencies for JPA and JUnit

### CODE REVIEW

**Review by AminZeina — CHANGES_REQUESTED** [review]
The Entity looks good and has all the initial fields we need to start/continue #19 and #30 which is great.
I think it would be good to have a unit test for this though. I know its simple and the tests will be trivial but it's probably best to have unit tests for all of our entities (especially a core one like this)

**Comment by pathumd** [comment]
@AminZeina for sure. Was debating whether I would develop tests for the entity in a separate test-development branch, but it makes sense to do it here

**Comment by AminZeina** [comment]
Ah I see, yeah might as well do it here that way we can test before deploying to main

**Comment by pathumd** [comment]
- Created AccountRepository class for managing persistence of Account entities
- Implemented JUnit tests for the Account class, including a test to verify the proper persistence of Account entities
- Added toString() method for Account

**Review by AminZeina — APPROVED** [review]
Tests are great and all pass locally, perfect!

**Review by yehandesilva — APPROVED** [review]
Looks good. The schema for account makes sense for our requirements and as you noted, we can add the relationship to its surveys once we implement surveys. 

JUnit tests look good and all pass.

**Comment by MichaelKyrollos** [comment]
Tests look great, entity is what we discussed/agreed on. Good to go!

**Review by MichaelKyrollos — APPROVED** [review]
Tests look great, entity is what we discussed/agreed on. Good to go!

**Pull request merged**
