### PR TITLE
Creating Early prototype ER Diagram and Model Diagram

### LINKED ISSUE #21: Create Early-Prototype Diagrams
Create our database diagrams depicting our structure so far for the first milestone.

### PR DESCRIPTION
**Pull request by MichaelKyrollos**
**Summary**
This PR closes #21 by adding database diagrams that represent the current data structure for Milestone 1 of our application. Also updated the README instructions. 

**Diagrams:**
Created diagrams showing our database entity defined in Milestone 1.
Added a current folder that contains the latest version of the database diagram.

**Versioning:**
As the project progresses, each milestone will have its own folder to archive previous versions of the diagrams.
For example, when Milestone 2 is reached, the diagram reflecting Milestone 2 will move to the current folder, and the Milestone 1 diagram will be moved to a dedicated folder for archiving.

### CODE REVIEW

**Review by yehandesilva — CHANGES_REQUESTED** [review]
I like how the README displayes the latest diagrams.

I believe for the ER diagram, primary keys need to be underlined. 
@pathumd Can you verify this as I know you may know more about this. Can you also make sure the diagram reflects the Account entity you created in #18.

**Review by pathumd — CHANGES_REQUESTED** [review]
As per @yehandesilva 's suggestion, for the ER diagram, the primary keys should be underlined (in this case, id) . In addition, specifically for ER diagrams, I believe that the type of each attribute can be omitted (since this is only necessary for UML class diagrams). Another small issue I found with the UML class diagram for the Account class is that the second constructor for Account should be public (+) instead of protected (#). Other than that, good work with the ER and UML class diagrams!

**Comment by MichaelKyrollos** [comment]
Will address them, thank you

**Comment by MichaelKyrollos** [comment]
@pathumd @yehandesilva updated the changes

**Review by yehandesilva — APPROVED** [review]
Changes look good.

**Review by pathumd — APPROVED** [review]
Changes are good, great work!

**Review by AminZeina — APPROVED** [review]
Diagrams look good to me, clean and accurate!

**Pull request merged**
