### PR TITLE
Update Readme

### LINKED ISSUE #80: Update README
Now that there is VertexAI integrated in the project, some of the instructions for how to run the project have changed.

### PR DESCRIPTION
**Pull request by MichaelKyrollos**
After doing the #77 , there is now some needed setup in order to get the AI running locally. 

This PR closes #80

### CODE REVIEW

**Review by yehandesilva — APPROVED** [review]
I would also add the step of restarting your computer for the API key as I had to do that for it to work.

**Review by AminZeina — CHANGES_REQUESTED** [review]
I also had to restart my computer after adding the environment variable (After Step 4.b). With that change, everything works as expected and instructions are clear.

**Review by pathumd — APPROVED** [review]
Other than the issue described above, the README looks good to me Michael. Good work

**Review by AminZeina — APPROVED** [review]

**Comment by AminZeina** [comment]
With the changes all looks good, nice update!

**Pull request merged**
