### PR TITLE
Create POST Survey Endpoint

### PR DESCRIPTION
**Pull request by MichaelKyrollos**
### **Summary:**
This pull request introduces two key endpoints to handle survey creation and retrieval. 

1. **POST /user/survey**: Allows authenticated users to create a new survey.
2. **GET /survey/{surveyId}**: Retrieves a survey by its ID.

#### **POST /user/survey**
   This endpoint allows authenticated users to create a survey. The user must be logged in to create a survey.

   **Request Body Example:**
   ```json
   {
       "description": "Survey",
       "closed": false,
       "questions": [
           {
               "question": "Describe your work experience.",
               "type": "TextQuestion"
           },
           {
               "question": "What's your favorite video game?",
               "type": "ChoiceQuestion",
               "options": [
                   { "description": "Fortnite" },
                   { "description": "Forza" },
                   { "description": "Mario-Kart" }
               ]
           },
           {
               "question": "What's your age?",
               "type": "NumberQuestion",
               "minValue": 0,
               "maxValue": 100
           },
           {
               "question": "Describe your work experience.",
               "type": "TextQuestion"
           }
       ]
   }
   ```

---

#### **GET /survey/{surveyId}**
   This endpoint retrieves the survey by its ID.

   **Response Example:**
   ```json
   {
       "surveyId": 1,
       "description": "Survey",
       "closed": false,
       "completions": [],
       "questions": [
           {
               "type": "ChoiceQuestion",
               "questionId": 2,
               "question": "What's your favorite video game?",
               "options": [
                   { "choiceOptionId": 1, "description": "Fortnite" },
                   { "choiceOptionId": 2, "description": "Forza" },
                   { "choiceOptionId": 3, "description": "Mario-Kart" }
               ]
           },
           {
               "type": "NumberQuestion",
               "questionId": 3,
               "question": "What's your age?",
               "minValue": 0,
               "maxValue": 100
           },
           {
               "type": "TextQuestion",
               "questionId": 1,
               "question": "Describe your work experience."
           },
           {
               "type": "TextQuestion",
               "questionId": 4,
               "question": "Describe your work experience."
           }
       ]
   }
   ```

---

### **Notes:**
- The `completions[]` and `closed` fields in the response are placeholders for future functionality. These will be addressed in an upcoming PR and are retained for now until we create the admin view.

---

#### **Successful GET of Survey:**
image

#### **Successful POST of a Survey:**
image

#### **Getting a Non-Existent Survey:**
image

#### **Trying to Create a Survey When Not Logged In:**
image

#### **UI View:**
image

### CODE REVIEW

**Review by AminZeina — APPROVED** [review]
Looks great, the endpoints both work as expected when testing manually through the interface, and the tests look good. Nice changes! This unblocks completion of #54 which is great.

**Review by pathumd — COMMENTED** [review]
Nice work Michael! After doing some manual testing, there is one piece of functionality that seems to have been broken after your changes. After entering a survey code and going to the Survey page to fill out a survey, clicking the Login button should keep the user on the Survey page (no redirecting) and display their account email under the Survey title. This functionality doesn't seem to be working anymore, as logging in redirects the user to their account (Home) page instead. Re-ran the previously merged branch to confirm it was working originally. It's interesting because you haven't touched the frontend at all other than vite.config.js so I'm not sure what could be the cause.

Another small thing to note is that getting a survey (i.e. entering the survey code) doesn't seem to work when launching the frontend on localhost:5173, but does work on localhost:8080)

**Review by yehandesilva — APPROVED** [review]
Looks good. I believe thats all the controller functionality done for this milestone. Just need to interface it with the frontend.

**Review by pathumd — APPROVED** [review]
In regards to my previous comment, @MichaelKyrollos running `mvn clean install` at the root as you suggested fixed the issue I was having. Thanks!

**Pull request merged**
