### PR TITLE
Alpha release diagrams

### LINKED ISSUE #47: Create Alpha Release Diagrams
Create Model UML class diagrams and database schema for our alpha release. This should be the complete representation of our project as no new fields or classes should be added in the next releases.

### PR DESCRIPTION
**Pull request by yehandesilva**
Closes #47 

Created Model UML diagrams and database ER diagrams.

These diagrams are likely final as our database entities should not change in future milestones.

### UML Diagram
- Based off the initial UML diagram discussed in #53 
- SurveyCompletion entity to track users who complete surveys to prevent duplicate responses
- Removed Response Entity entirely as it would only contain the id field that its sub classes would inherit (No point of using inheritence there)

### ER Diagram
- Showcases the actual database tables created through our entites
- Question table has been created as it has been annotated with "@Entity" even though it will never be instantiated
- Bi-directional relationships shown with the "many" side of the relationship containing the foreign key

### CODE REVIEW

**Comment by yehandesilva** [comment]
I couldn't figure out how to get the diagrams working in IntelliJ. 
I changed our database injection from H2 to Postgres and was able to automatically create an ER diagram from within the pg4 admin application. The relationships were overlapping and so I just created those myself.
Untitled

Good to know in for future projects so we don't need to do everything manually.

**Review by AminZeina — APPROVED** [review]
Nice work! Thanks for incorporating the changes discussed in #53, this looks great. ER diagrams are a good addition as well, and both they and the new UML diagrams look good.

**Review by pathumd — APPROVED** [review]
Diagrams look good @yehandesilva, all the attributes of entities and associations between them make sense. Good work! (Note: Something that #62 is addressing is adding an attribute called 'type' to the Question parent class, so we may need to update the Question entity after this PR is merged)

**Comment by yehandesilva** [comment]
If you are talking about the type of question, it does not need to be added. The inheritance strategy I chose to go with is to make each type of question its own table in the database. I could have gone with a single table, and it would require a discriminator key like the one you mentioned. 

I'm guessing you are passing the type as a key in the JSON request body. The controller will be tasked with determing the type of question and create a record in the corresponding table.

**Comment by pathumd** [comment]
> If you are talking about the type of question, it does not need to be added. The inheritance strategy I chose to go with is to make each type of question its own table in the database. I could have gone with a single table, and it would require a discriminator key like the one you mentioned.
> 
> I'm guessing you are passing the type as a key in the JSON request body. The controller will be tasked with determing the type of question and create a record in the corresponding table.

Yeah, just to clarify at the time I needed some way for the frontend to know what the 'type' of each question was (when the Survey entity is converted to JSON and returned as a response to the frontend). Since there was no explicit field that denoted the type, the JSON returned to the frontend had no way of knowing what the question type was. To have a 'type' key included in the response, adding a type attribute to the Question parent class (and setting it there) meant that all concrete implementations of Question would include it when they get converted to JSON.

**Review by MichaelKyrollos — CHANGES_REQUESTED** [review]
Do we inlcude DTO's in the UML? If so, unfortunately, you may need to do an update once more PRs are merged @yehandesilva

**Comment by yehandesilva** [comment]
No, we only need to show the diagrams of the models. So what I have right now is sufficient.

**Review by MichaelKyrollos — APPROVED** [review]

**Pull request merged**
