### PR TITLE
Fix/28 integrate frontend pom

### LINKED ISSUE #28: Integrate Frontend with pom.xml
As stated in the project requirements, we should have a single pom.xml that can be used to build and run our entire application, so we need to integrate our frontend into a single build using the pom.xml.

### PR DESCRIPTION
**Pull request by MichaelKyrollos**
**PR for Issue #28:**  
This closes #28 
As stated in the project requirements, we should have a single `pom.xml` in the root directory to build and run the entire application. This PR integrates the frontend and backend builds into a single build process managed by Maven, so users can run `mvn clean install` or `mvn package` without needing to navigate between directories.

**Summary of Changes:**
- The root `pom.xml` now serves as the parent for both frontend and backend modules.
- We included a `pom.xml` in the frontend directory, even though it’s not strictly necessary, to help Maven recognize the `package.json` file used by Vite (React). This enables Maven to handle frontend dependencies and build tasks consistently.
- The frontend `pom.xml` handles the `npm install` command to fetch and install dependencies before the backend build begins.

**Current Build and Run Process:**
1. From the root directory, run:
   ```bash
   mvn clean install
   ```
   This command installs dependencies and builds both the frontend and backend.
   
2. To run the application, navigate to the backend directory and start Spring Boot:
   ```bash
   mvn spring-boot:run
   ```
   This should launch the application on `localhost:8080`.

**Next Steps:**
- Currently, `mvn spring-boot:run` does not work directly from the root `pom.xml`. For now, you need to navigate to the backend directory and run it from there. Further work is needed to enable `spring-boot:run` directly from the root.

**Instructions for Reviewers:**
1. Pull the branch and run:
   ```bash
   mvn clean install
   ```
   or
   ```bash
   mvn package
   ```
   Make sure there are no errors during the build.
   
2. Test the application by running:
   ```bash
   mvn spring-boot:run
   ```
   from the backend directory. If you encounter any issues or errors, please let me know.

### CODE REVIEW

**Review by pathumd — CHANGES_REQUESTED** [review]
The build of the frontend and backend via the pom.xml in the root of the project is working as expected for me. After doing 'mvn clean install' at the root, and then doing the run command in the backend folder, the application is available at localhost:8080 and the frontend functions as expected.

One thing that I noticed when looking at the logs when 'npm install' is getting executed is the following:

```
[INFO] --- frontend:1.12.0:npm (npm install) @ monkeyPoll ---
[INFO] Running 'npm install' in /Users/pathumdanthanarayana/Library/CloudStorage/OneDrive-CarletonUniversity/School/Fall 2024/SYSC 4806/Group Project/monkeyPoll/frontend
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@eslint/config-array@0.18.0',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@eslint/core@0.7.0',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@eslint/eslintrc@3.1.0',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'globals@14.0.0',
[INFO] npm WARN EBADENGINE   required: { node: '>=18' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@eslint/js@9.14.0',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@eslint/object-schema@2.1.4',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@eslint/plugin-kit@0.2.2',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@humanfs/core@0.19.1',
[INFO] npm WARN EBADENGINE   required: { node: '>=18.18.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@humanfs/node@0.16.6',
[INFO] npm WARN EBADENGINE   required: { node: '>=18.18.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@humanwhocodes/retry@0.3.1',
[INFO] npm WARN EBADENGINE   required: { node: '>=18.18' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@humanwhocodes/retry@0.4.1',
[INFO] npm WARN EBADENGINE   required: { node: '>=18.18' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: '@vitejs/plugin-react@4.3.3',
[INFO] npm WARN EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'eslint@9.14.0',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'eslint-scope@8.2.0',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'eslint-visitor-keys@4.2.0',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'espree@10.3.0',
[INFO] npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'file-entry-cache@8.0.0',
[INFO] npm WARN EBADENGINE   required: { node: '>=16.0.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'flat-cache@4.0.1',
[INFO] npm WARN EBADENGINE   required: { node: '>=16' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'globals@15.12.0',
[INFO] npm WARN EBADENGINE   required: { node: '>=18' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'rollup@4.25.0',
[INFO] npm WARN EBADENGINE   required: { node: '>=18.0.0', npm: '>=8.0.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] npm WARN EBADENGINE Unsupported engine {
[INFO] npm WARN EBADENGINE   package: 'vite@5.4.10',
[INFO] npm WARN EBADENGINE   required: { node: '^18.0.0 || >=20.0.0' },
[INFO] npm WARN EBADENGINE   current: { node: 'v14.17.0', npm: '7.20.0' }
[INFO] npm WARN EBADENGINE }
[INFO] 
[INFO] up to date, audited 259 packages in 766ms
[INFO] 
[INFO] 102 packages are looking for funding
[INFO]   run `npm fund` for details
[INFO] 
[INFO] found 0 vulnerabilities
[INFO] 
[INFO] --- frontend:1.12.0:npm (npm build) @ monkeyPoll ---
[INFO] Running 'npm run build' in /Users/pathumdanthanarayana/Library/CloudStorage/OneDrive-CarletonUniversity/School/Fall 2024/SYSC 4806/Group Project/monkeyPoll/frontend
[INFO] 
[INFO] > frontend@0.0.0 build
[INFO] > vite build
[INFO] 
[INFO] (node:33321) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '??='
[INFO]     at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
[INFO] (Use `node --trace-warnings ...` to show where the warning was created)
[INFO] (node:33321) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[INFO] (node:33321) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It appears that the node version that you used is too outdated, so maybe it should be upgraded to avoid these warnings (and potentially that syntax error at the end caused by 'vite build'?). Other than that, the integration is functioning for me. Good work!

**Comment by MichaelKyrollos** [comment]
Thank you @pathumd! I have updated the node versions. Please try running it again and let me know if you get the same errors

**Comment by MichaelKyrollos** [comment]
Created an issue for running ``mvn spring-boot: run`` from the root. 
issue: #36

**Review by yehandesilva — APPROVED** [review]
Build instructions worked. Running `mvn clean install` built the frontend and backend and the pom.xml is now in the root directory, which makes it easier to build.

You can add `frontend/node` to the gitignore as it gets created upon building the project.

**Review by pathumd — APPROVED** [review]

**Comment by pathumd** [comment]
New changes have resolved the warning logs and the build and frontend and backend still function as expected. Nice work

**Comment by AminZeina** [comment]
Looks good! I was able to build and run the jar, which successfully ran the app correctly. Approved!

**Review by AminZeina — APPROVED** [review]

**Pull request merged**
