### PR TITLE
#56: Initial Implementation of GET /survey Controller

### PR DESCRIPTION
**Pull request by MichaelKyrollos**
### Description

**Implemented Features:**
- Developed the initial `GET /survey` controller.
- Added survey details in the response, including:
  - `surveyId`
  - `description`
  - `status` (`closed`)
  - `completions` (list of completed responses)
  - `questions` (with associated details).

**Sample Response Body:**
```json
{
    "surveyId": 1,
    "description": "Test Survey",
    "closed": false,
    "completions": [],
    "questions": [
        {
            "questionId": 2,
            "question": "Test Question",
            "minValue": 0,
            "maxValue": 0
        },
        {
            "questionId": 1,
            "question": "Test Question"
        }
    ]
}
```

**Notes:**
- JSON annotations (`@JsonIgnore`) have been applied. Please review these carefully to ensure they align with our intended functionality.
- For now, the controller is unauthenticated due to incomplete functionality in `SecurityConfig`. This should be addressed once the controller is finalized.
- Included a screenshot showing the controller working in a simulated environment using Postman.  
image

---

### Additional Context
- Further work is required to implement the POST functionality for surveys, which is pending the completion of #54.
- @AminZeina, could you confirm possibly how we will do the Security Config for this endpoint
---

**Closes:** #56

### CODE REVIEW

**Review by pathumd — APPROVED** [review]
Your changes look good to me Michael; the /survey endpoint you created, and the format for the returned JSON is what I was expecting for my frontend to receive. It's also good that you made sure to leave out certain attributes of the Survey entity in the returned JSON response (which in this case, any user shouldn't know about). Good work!

**Review by AminZeina — CHANGES_REQUESTED** [review]
Overall nice changes, looks good! This adds a lot of core functionality to our app

One thing we might want to add is the question type for each question, which might make it easier to load a survey on the frontend #43 , @pathumd would this help?

For the Authentication, your changes to SecurityConfig are correct if this endpoint is supposed to be unauthenticated (which I think is what we wanted?). Although I think we actually need 2 endpoints for getting surveys, one for user's trying to fill in the survey (unauth) and then one for when the survey owner wants to get the survey responses/completions (auth). Right now it looks like this endpoint does both. So I think we should make make this endpoint the unauthenticated endpoint used for users to fill out surveys, including:
   - remove the `completions` field from the response
   - possibly also remove the `closed` field (if a survey is closed, we should probably just send a message back to the user)
   - this endpoint will be used for #43 

Then create a new **authenticated** endpoint, something like `/user/survey/{id}` (perhaps in the account controller?) which returns the administrative info:
  - Return the survey ID, description, status, and completions
  - No need to return the questions themselves
  - This endpoint will be used for #49 

Lastly for the create survey POST, #54 is actually waiting on this to be completed. Right now the JSON that will be send to this POST endpoint is defined in #54. All that's left to do for it is to handle the response from the endpoint, which is why #54 is blocked

**Comment by MichaelKyrollos** [comment]
Thank you both for the feedback. I will address @AminZeina changes in another PR so that @pathumd can do his work

**Review by AminZeina — APPROVED** [review]
Sounds good to me. In that case, approved!

**Pull request merged**
