### PR TITLE
Feature/Create Home Screen 

### LINKED ISSUE #29: Create Home Screen
Our frontend currently only has a welcome screen with no home screen.

Once a user successfully enters a valid survey code or logs in, it should route them to the home screen. This needs to be done after #20. We should make our app a single-page-application, so don't use React's clientside Router or BrowserRouter as I have heard it interferes with our backend calls.

I've already created 2 contexts that should be available throughout the entire app via the useContext hook. 
If user or survey are not null, it should navigate the user to the home screen, otherwise it should remain on the welcome screen.
Within the home screen, if only survey is not null, we should still show the login button along with the survey they are trying to complete. If only user is not null, they should see a list of surveys as well as the ability to create their own survey. If both are not null, it is a logged in user trying to complete a survey and the login button should not appear. 

We don't need all the components currenty, but the logic should be finished.

### PR DESCRIPTION
**Pull request by MichaelKyrollos**
### Summary

**This PR closes #29** by adding a new `Home.jsx` component as the homepage displayed upon successful login. The `Home` component provides a personalized welcome message for logged-in users, with their first name, last name, and email, as well as a message about password security. 

Additionally:
- **UserContext and Login Flow Enhancements**: 
  - Updated `LoginDialog.jsx` and `Register.jsx` components to use `PropTypes` for validation.
  - `Welcome.jsx` now redirects to `Home` when a user or survey is detected, ensuring a seamless user experience post-login or survey access.

### CODE REVIEW

**Review by AminZeina — CHANGES_REQUESTED** [review]
Good additions, login and registration work as expected and user info is displayed with all the correct info (nice password note 💯 ). 

The only issue I see is that the login button is still visible after login. Ideally we should have this be a logout button which returns the user back to the welcome screen. It would be worthwhile to add this before deploying these changes.

**Comment by MichaelKyrollos** [comment]
> Good additions, login and registration work as expected and user info is displayed with all the correct info (nice password note 💯 ).
> 
> The only issue I see is that the login button is still visible after login. Ideally we should have this be a logout button which returns the user back to the welcome screen. It would be worthwhile to add this before deploying these changes.


Thank you for the feedback! I've updated the branch with those changes

**Review by pathumd — APPROVED** [review]
After performing some manual testing, registering for a new account and logging in does properly load a Home Screen where the user's account info is displayed. The logout button works as expected and directs the user back to the login page. For the next milestone, we can decide what exactly needs to be displayed and accessible for the user within the home page. Good work Michael!

**Review by AminZeina — APPROVED** [review]
Looks great! Thanks for making the changes. The `login` button changes to `logout` after logging in, and then back to `login`. I'm able to create multiple accounts and log in and out of each of them; when I do so, the correct user info is displayed on the new home screen. Great work!

**Review by yehandesilva — APPROVED** [review]
Looks good. Handling of user sign up and login works as expected.

**Pull request merged**
